### ISSUE TITLE
Bug Tracker

### ISSUE THREAD

**Issue by TingyiChen** [TingyiChen/device_xiaomi_vince#1]
To track unsolved bug.(May rebase at anytime if necessary)

**Comment by TingyiChen** [comment]
Camera

**Comment by TingyiChen** [comment]
Goodix fingerprint

**Comment by TingyiChen** [comment]
Music audio output

**Comment by karthick111** [comment]
Uh

**Comment by TingyiChen** [comment]
@karthick111:stuck_out_tongue:

**Comment by obsvg216** [comment]
And the assembly is launched?

**Comment by obsvg216** [comment]
Ril not working,but camera work with blobs 8.1.11 miui

**Comment by TingyiChen** [comment]
@obsvg216 with this blob list?https://github.com/TingyiChen/device_xiaomi_vince/blob/cm-14.1/proprietary-files.txt

**Comment by obsvg216** [comment]
Whith full camera libs from stock rom.Cameraserver,jnicamera.. and more.I am flashing patch whith libs and camera working,but ril not working,maybe it's worth trying to take a ril from oxygen xiaomi,they have a fully working Los with a pre-kernel

**Comment by TingyiChen** [comment]
@obsvg216 mind send that patch?😂seems need to hex edit to fix camera

**Comment by obsvg216** [comment]
Now the camera is not as important as the scanner and mobile network

**Comment by TingyiChen** [comment]
?What's scanner (network will fix by reverting to old ril)

**Comment by obsvg216** [comment]
Fingerprint goodix not work

**Comment by obsvg216** [comment]
can you return the old ril?

**Comment by TingyiChen** [comment]
Goodix hal need wrapper,ril will be fixed after I got permanent fix for cam

**Comment by bju2000** [comment]
Will this do?

https://github.com/HighwayStar/android_device_xiaomi_mido_fingerprint-goodix

**Comment by TingyiChen** [comment]
@bju2000 maybe won't work because no ioctl commands (already fixed goodix)

**Comment by TingyiChen** [comment]
Seems all fixed

**Comment by darshan1205** [comment]
VoLTE ?

**Comment by chaubeyprateek** [comment]
Volte works
