### ISSUE TITLE
Accessing camera functions in apps results in Force Close

### ISSUE THREAD

**Issue by nelske** [TingyiChen/device_xiaomi_vince#3]
When opening whatsapp and either pressing the camera icon in a chat or using the Whatsapp web function (qr code scan), the application force closes.

**LOS version:** 14.1-20180212-UNOFFICIAL-vince
**Device type:** 4gb/64gb

**Steps to reproduce:**
1: Open whatsapp
2: Open Settings menu > Whatsapp Web > press next 
or
3: Open a chat, press the camera icon in the textbox

Logcat attached: [Logcat.txt](https://github.com/TingyiChen/device_xiaomi_vince/files/1720295/Logcat.txt)

**Comment by darshan1205** [comment]
@TingyiChen disable hal3

**Comment by TingyiChen** [comment]
@darshan1205 same

**Comment by nelske** [comment]
Read this in the telegram app:

Remove these props:
`camera.hal1.packagelist=com.skype.raider,com.google.android.talk
media.camera.ts.monotonic=1
persist.camera.gyro.android=1
persist.camera.is_type=1
vidc.debug.perf.mode=2
vidc.enc.dcvs.extra-buff-count=2
vidc.enc.disable.pq=true
persist.camera.HAL3.enabled=1`


Add these:
`camera.display.umax=1920x1080
camera.display.lmax=1280x720
camera.hal1.packagelist=com.skype.raider,com.google.android.talk
media.camera.ts.monotonic=1
persist.camera.gyro.android=1
persist.camera.HAL3.enabled=0
persist.camera.is_type=1
vidc.enc.narrow.searchrange=1`

**Comment by TingyiChen** [comment]
LineageOS SRC Issue.

**Comment by nelske** [comment]
Not fixed for me
