### ISSUE TITLE
No sound on headphones connected to audio jackplug.

### ISSUE THREAD

**Issue by nelske** [TingyiChen/device_xiaomi_vince#4]
When connecting headphones via the audio jackplug, there is no sound. Playback works via speakers.
I can hear a slight static noise in the background but could just be me.

**LOS version:** 14.1-20180212-UNOFFICIAL-vince
**Device type:** 4gb/64gb

**Steps to reproduce:**
1: Attach headphones to 3.5mm audio jack
2: play something (youtube / music player)

Logcat attached, it holds the log of the above actions so including plugging in headphones, playing YouTube video, stopping it and unplugging headphones.: 
[Logcat audio jack.txt](https://github.com/TingyiChen/device_xiaomi_vince/files/1720326/Logcat.audio.jack.txt)

**Comment by nelske** [comment]
Zip posted earlier seems to fix it: 
[audio.zip](https://github.com/TingyiChen/device_xiaomi_vince/files/1720359/audio.zip)

**Comment by nelske** [comment]
Oops, closed by mistake.

**Comment by TingyiChen** [comment]
Fixed.
